### ISSUE TITLE
It's better to have a details about this project 

### ISSUE THREAD

**Issue by MubarakNative** [maheshwaran01m/Demo#1]
If you can, add a **README.md** to inform about the project and **license** to ensure this project complies with OSS, without any license this project become proprietary to only one, no others can contribute this project.

**Comment by maheshwaran01m** [comment]
@MubarakNative  I have updated the license. In Future I will update the readme in detail. Thanks 🧑‍💻

**Comment by MubarakNative** [comment]
OK Tamil ah bro?
